### PR TITLE
+ operator for strings

### PR DESCRIPTION
**Pull request by ix-dcourtois**
Here is a proposition for supporting concatenation of strings through the + binary operator.
- Doesn't modify generated code for numerical operands
- Handle both LLVM and Interpreter
- Included unit tests

### CODE REVIEW

**Comment by davvid** [comment]
@jberlin will be reviewing these PRs soon.  We hope to get to them by the end of the week.  Thanks again!

**Comment by jberlin** [comment]
Update: targeting Monday (7/24) to do some testing and verification with our in-house tools.

**Comment by ix-dcourtois** [comment]
Hi, Any news on this one ?

**Comment by jberlin** [comment]
Hi Damien. I'm going to pull these 3 in, then merge with our internal code base and make a new pull request later with some other changes we've done internally. That should sync us all up inside out. Thanks!

**Pull request merged**
